# Generated by Django 5.0.3 on 2024-03-09 07:28

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mars_client', '0006_alter_report_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='context',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст отчёта'),
        ),
    ]
