# Generated by Django 5.0.3 on 2024-03-09 05:31

from django_ckeditor_5.fields import CKEditor5Field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mars_client', '0004_alter_report_send_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='context',
            field=CKEditor5Field(verbose_name='Текст отчёта', config_name='context'),
        ),
    ]
